name: presence_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  get: 4.6.1
  cupertino_icons: ^1.0.2
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  cloud_firestore: 4.8.1
  firebase_storage: 11.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

